AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CloudFormation template to create a lambda that loads a
  scikit-learn model from S3 and executes it.

Resources:
  ScikitLearnFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scikit_learn_lambda.handler
      Runtime: python3.7
      MemorySize: 1024
      Environment:
        Variables:
          SKLEARN_MODEL_PATH: "s3://model.joblib"
      Layers:
        - arn:aws:lambda:us-west-2:446751924810:layer:test-scikit-learn-layer:6
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/predict'
            Method: post
